### ISSUE TITLE
installation issue on Ubuntu 18.04

### ISSUE THREAD

**Issue by vin-d** [lokedhs/cl-rabbit#9]
Hi,
is there some instructions to install on Ubuntu 18 ?
I'm using emacs+slime+sbcl

and ``(ql:quickload "cl-rabbit")`` fails because of cffi-libffi fails upon cffi-grovel.
Any idea why that would fail ? am I the only one having this issue or am I the only one using cl-rabbit with Ubuntu ?

Thanks.

**Comment by lokedhs** [comment]
You need to install libffi from the Ubuntu repositories. I think the package is called libffi-dev, but I dont' have an Ubuntu system nearby to test on. Please let me know if this doesn't help.

**Comment by vin-d** [comment]
Perfect, ``sudo apt install libffi-dev`` it did help.
I was tangled in dependencies problem because I had also the wonderful idea to 
-  ``sudo install cl-cffi``
- build the newest libffi from https://github.com/libffi/libffi and `` sudo make install `` it. --> this installs only a 64 bit version that cl-rabbit do not like.

So I also had to revert that.

**Comment by lokedhs** [comment]
That should work though. Are you running a 32-bit version of SBCL?

Also, I would not recommend installing any CL libraries from the Ubuntu repositories. Use Quicklisp instead. That way you get the latest versions of everything.

**Comment by vin-d** [comment]
Yes I'm new to lisp and I'll now stay with Quicklisp for the libs.
I use 64-bit SBCL.

As far as I understand, this bug (undefined symbol FFI_SYSV https://bugs.launchpad.net/cffi/+bug/1692751) appears if I build and instal latest libffi instead of using the one from Ubuntu repo.
